"""add internal receipt support to invoice

Revision ID: 03f232cb12c4
Revises: 686ab7aefb17
Create Date: 2026-05-02 12:04:42.312560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f232cb12c4'
down_revision = '686ab7aefb17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('invoices', sa.Column('internal_number', sa.Integer(), nullable=True))
    op.alter_column('invoices', 'afip_invoice_log_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'document_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'document_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_invoices_internal_number'), 'invoices', ['internal_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_internal_number'), table_name='invoices')
    op.alter_column('invoices', 'document_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'document_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'afip_invoice_log_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'internal_number')
    op.drop_column('invoices', 'is_internal')
    # ### end Alembic commands ###

