"""add nc back-pointers to invoice

Revision ID: 46bc580c138b
Revises: e40b6f9184ca
Create Date: 2026-05-02 13:21:33.087867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bc580c138b'
down_revision = 'e40b6f9184ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cancels_invoice_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('cancelled_by_invoice_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_cancelled_by_invoice_id'), 'invoices', ['cancelled_by_invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_cancels_invoice_id'), 'invoices', ['cancels_invoice_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'invoices', ['cancelled_by_invoice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'invoices', ['cancels_invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_cancels_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cancelled_by_invoice_id'), table_name='invoices')
    op.drop_column('invoices', 'cancelled_by_invoice_id')
    op.drop_column('invoices', 'cancels_invoice_id')
    # ### end Alembic commands ###

