"""add sent_at to proposals

Revision ID: 5561e434993b
Revises: 46bc580c138b
Create Date: 2026-05-02 15:28:53.794540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5561e434993b'
down_revision = '46bc580c138b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Backfill aproximado: sent_at = updated_at para registros ya enviados/aceptados/rechazados
    op.execute(
        "UPDATE proposals SET sent_at = updated_at WHERE status IN ('sent', 'accepted', 'rejected')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'sent_at')
    # ### end Alembic commands ###

