"""add cuit and iva_condition to clients

Revision ID: 601e661d3a6f
Revises: 87eb98fb6d79
Create Date: 2026-05-02 00:13:05.868321

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "601e661d3a6f"
down_revision = "87eb98fb6d79"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("cuit", sa.String(length=11), nullable=True))
    op.add_column("clients", sa.Column("iva_condition", sa.String(length=2), nullable=True))
    op.create_index(op.f("ix_clients_cuit"), "clients", ["cuit"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_cuit"), table_name="clients")
    op.drop_column("clients", "iva_condition")
    op.drop_column("clients", "cuit")
    # ### end Alembic commands ###
