"""add address to client

Revision ID: 686ab7aefb17
Revises: bb2101802a31
Create Date: 2026-05-02 11:33:37.337590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686ab7aefb17'
down_revision = 'bb2101802a31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###

