"""add afip_token and afip_invoice_log tables

Revision ID: 87eb98fb6d79
Revises: 813874f5ecdd
Create Date: 2026-05-01 21:21:41.189292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87eb98fb6d79'
down_revision = '813874f5ecdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afip_invoice_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_of_sale', sa.Integer(), nullable=False),
    sa.Column('receipt_type', sa.Integer(), nullable=False),
    sa.Column('request_xml', sa.Text(), nullable=False),
    sa.Column('receipt_number', sa.Integer(), nullable=True),
    sa.Column('cae', sa.String(length=32), nullable=True),
    sa.Column('cae_expiration', sa.Date(), nullable=True),
    sa.Column('authorized_cbte_tipo', sa.Integer(), nullable=True),
    sa.Column('response_xml', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_afip_invoice_log_id'), 'afip_invoice_log', ['id'], unique=False)
    op.create_index('ix_afip_invoice_log_pos_type_number', 'afip_invoice_log', ['point_of_sale', 'receipt_type', 'receipt_number'], unique=False)
    op.create_table('afip_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('sign', sa.Text(), nullable=False),
    sa.Column('generation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_afip_token_id'), 'afip_token', ['id'], unique=False)
    op.create_index(op.f('ix_afip_token_service'), 'afip_token', ['service'], unique=False)
    op.create_index('ix_afip_token_service_expiration', 'afip_token', ['service', 'expiration_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_afip_token_service_expiration', table_name='afip_token')
    op.drop_index(op.f('ix_afip_token_service'), table_name='afip_token')
    op.drop_index(op.f('ix_afip_token_id'), table_name='afip_token')
    op.drop_table('afip_token')
    op.drop_index('ix_afip_invoice_log_pos_type_number', table_name='afip_invoice_log')
    op.drop_index(op.f('ix_afip_invoice_log_id'), table_name='afip_invoice_log')
    op.drop_table('afip_invoice_log')
    # ### end Alembic commands ###

