"""add invoices table

Revision ID: bb2101802a31
Revises: 601e661d3a6f
Create Date: 2026-05-02 00:48:18.146225

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bb2101802a31"
down_revision = "601e661d3a6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
