"""add cancelled_at to invoice

Revision ID: e40b6f9184ca
Revises: 93481de3130b
Create Date: 2026-05-02 13:06:43.445925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40b6f9184ca'
down_revision = '93481de3130b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'cancelled_at')
    # ### end Alembic commands ###

