"""add pdf templates table

Revision ID: ef32bc13f2fe
Revises: f0e4f495abc8
Create Date: 2026-04-13 22:24:32.829074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef32bc13f2fe'
down_revision = 'f0e4f495abc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('bg_color', sa.String(length=7), server_default='#ffffff', nullable=False),
    sa.Column('text_color', sa.String(length=7), server_default='#1a1a1a', nullable=False),
    sa.Column('accent_color', sa.String(length=7), server_default='#2563eb', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_templates_id'), 'pdf_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_templates_id'), table_name='pdf_templates')
    op.drop_table('pdf_templates')
    # ### end Alembic commands ###

